insert into JobDesc (JobID, JobDescription) values (8015, 'Esophageal anomaly NEC');
insert into JobDesc (JobID, JobDescription) values (1956, 'Dysmetabolic syndrome x');
insert into JobDesc (JobID, JobDescription) values (3405, 'Synovitis NOS');
insert into JobDesc (JobID, JobDescription) values (4263, 'Buphthal w oth eye anom');
insert into JobDesc (JobID, JobDescription) values (2883, 'Fx humer, lat condyl-cl');
insert into JobDesc (JobID, JobDescription) values (8251, 'Deep 3 deg brn upper arm');
insert into JobDesc (JobID, JobDescription) values (7946, 'Retain prod concept-unsp');
insert into JobDesc (JobID, JobDescription) values (3500, 'Ch embl thorac vein NEC');
insert into JobDesc (JobID, JobDescription) values (8038, 'Quads w fetal loss-ante');
insert into JobDesc (JobID, JobDescription) values (5425, 'Syphilitic alopecia');
insert into JobDesc (JobID, JobDescription) values (4367, 'Cardiac murmurs NEC');
insert into JobDesc (JobID, JobDescription) values (9736, 'Hx-congenital malfor NEC');
insert into JobDesc (JobID, JobDescription) values (9217, 'Acq neck deformity');
insert into JobDesc (JobID, JobDescription) values (1617, 'Mumps orchitis');
insert into JobDesc (JobID, JobDescription) values (1927, 'Rupt flexor tendon hand');
insert into JobDesc (JobID, JobDescription) values (1029, 'Herpes simplex NOS');
insert into JobDesc (JobID, JobDescription) values (9856, 'Leucocoria');
insert into JobDesc (JobID, JobDescription) values (6394, 'Hx-female genit malg NOS');
insert into JobDesc (JobID, JobDescription) values (3845, 'Postherpes polyneuropath');
insert into JobDesc (JobID, JobDescription) values (8392, 'Cross country skiing');
