insert into Potential_Employee (PempID  ) values (21);
insert into Potential_Employee (PempID  ) values (22);
insert into Potential_Employee (PempID ) values (23);
insert into Potential_Employee (PempID ) values (24);
insert into Potential_Employee (PempID ) values (25);
insert into Potential_Employee (PempID ) values (26);
insert into Potential_Employee (PempID) values (27);
insert into Potential_Employee (PempID ) values (28);
insert into Potential_Employee (PempID) values (29);
insert into Potential_Employee (PempID) values (30);